### ISSUE TITLE
最下方的資訊區塊沒有置中

### ISSUE THREAD

**Issue by YueLinHo** [benwang0912/WP2016Project#1]
Link: https://benwang0912.github.io/WP2016Project/
瀏覽器: Google Chrome
螢幕解析度: 1920 X 1080

如下圖:

![image](https://cloud.githubusercontent.com/assets/5831804/20162988/d351daf6-a733-11e6-8109-4c5851d1b0ef.png)

**Comment by benwang0912** [comment]
Solved, thanks a lot.  : )

**Comment by YueLinHo** [comment]
Fixed by 9242d58047c9293db3cb8b273cde0535ec57308c.

> Solved, thanks a lot. : )

@benwang0912 You're welcome! ^_^

**Comment by YueLinHo** [comment]
下次你可以在 commit log message 的 Subject 使用「Fixed issue #xxx: ...」(xxx 是 issue No.)
這樣 GitHub 會自動幫你 close 相關的 issue

P.S. Subject 指的是 log message 的第一行
(一般第二行是空行，第三行開始叫 body，這個格式來自 email 格式)
